// ============================================================
// Quantum Cancer Detection – Embedded Data Layer
// Real values from pipeline outputs + simulated deep/quantum metrics
// ============================================================

const QCD_DATA = {

  // ── Dataset Statistics (from quality_report.json) ──────────────────────
  dataset: {
    totalImages: 130002,
    cleanImages: 128684,
    corruptedImages: 0,
    duplicatesRemoved: 1318,
    abnormalDimensions: 3,
    extremelyBlurred: 0,
    cancerTypes: 9,
    subClasses: 26,
    trainSplit: 0.70,
    valSplit: 0.15,
    testSplit: 0.15,
    imageSize: 224,
    featureDimension: 3328,
  },

  // ── Cancer Type Definitions ─────────────────────────────────────────────
  cancerTypes: [
    {
      id: "leukemia",
      name: "Leukemia (ALL)",
      icon: "ALL",
      color: "#ff4757",
      description: "Acute Lymphoblastic Leukemia – cancer of the blood and bone marrow affecting white blood cells.",
      subTypes: ["all_benign", "all_early", "all_pre", "all_pro"],
      subTypeLabels: ["Benign", "Early Stage", "Pre-B", "Pro-B"],
      images: 14951,
      accuracy: 0.9821,
    },
    {
      id: "brain",
      name: "Brain Cancer",
      icon: "CNS",
      color: "#6366f1",
      description: "Intracranial tumors including glioma, meningioma, and general brain tumors classified via MRI.",
      subTypes: ["brain_glioma", "brain_menin", "brain_tumor"],
      subTypeLabels: ["Glioma", "Meningioma", "General Tumor"],
      images: 15000,
      accuracy: 0.9743,
    },
    {
      id: "breast",
      name: "Breast Cancer",
      icon: "BRC",
      color: "#3b82f6",
      description: "Histopathological classification of breast tissue into benign and malignant categories.",
      subTypes: ["breast_benign", "breast_malignant"],
      subTypeLabels: ["Benign", "Malignant"],
      images: 9997,
      accuracy: 0.9912,
    },
    {
      id: "cervical",
      name: "Cervical Cancer",
      icon: "CX",
      color: "#f59e0b",
      description: "Cervical cell classification across 5 Pap smear categories including dyskeratosis, koilocytosis, and metaplasia.",
      subTypes: ["cervix_dyk", "cervix_koc", "cervix_mep", "cervix_pab", "cervix_sfi"],
      subTypeLabels: ["Dyskeratosis", "Koilocytosis", "Metaplasia", "Parabasal", "Superficial-Intermediate"],
      images: 4049,
      accuracy: 0.9567,
    },
    {
      id: "kidney",
      name: "Kidney Cancer",
      icon: "REN",
      color: "#10b981",
      description: "Renal CT scan classification distinguishing normal kidney tissue from tumorous regions.",
      subTypes: ["kidney_normal", "kidney_tumor"],
      subTypeLabels: ["Normal", "Tumor"],
      images: 10000,
      accuracy: 0.9889,
    },
    {
      id: "colon",
      name: "Colon Cancer",
      icon: "CRC",
      color: "#059669",
      description: "Colon biopsy classification from histopathological slides into adenocarcinoma and benign tissue.",
      subTypes: ["colon_aca", "colon_bnt"],
      subTypeLabels: ["Adenocarcinoma", "Benign Tissue"],
      images: 10000,
      accuracy: 0.9978,
    },
    {
      id: "lung",
      name: "Lung Cancer",
      icon: "LUN",
      color: "#2563eb",
      description: "Pulmonary histopathology slides classified into adenocarcinoma, benign tissue, and squamous cell carcinoma.",
      subTypes: ["lung_aca", "lung_bnt", "lung_scc"],
      subTypeLabels: ["Adenocarcinoma", "Benign Tissue", "Squamous Cell"],
      images: 15000,
      accuracy: 0.9854,
    },
    {
      id: "lymphoma",
      name: "Lymphoma",
      icon: "LYM",
      color: "#4f46e5",
      description: "Lymph node biopsy classification into Chronic Lymphocytic Leukemia, Follicular, and Mantle Cell Lymphoma subtypes.",
      subTypes: ["lymph_cll", "lymph_fl", "lymph_mcl"],
      subTypeLabels: ["CLL", "Follicular", "Mantle Cell"],
      images: 10000,
      accuracy: 0.9736,
    },
    {
      id: "oral",
      name: "Oral Cancer",
      icon: "ORL",
      color: "#d97706",
      description: "Oral cavity scan classification distinguishing normal oral tissue from squamous cell carcinoma lesions.",
      subTypes: ["oral_normal", "oral_scc"],
      subTypeLabels: ["Normal", "SCC"],
      images: 3000,
      accuracy: 0.9802,
    },
  ],

  // ── Model Performance Metrics ───────────────────────────────────────────
  models: {
    "Random Forest": {
      accuracy: 0.9645,
      sensitivity: 0.9481,
      specificity: 0.9954,
      precision: 0.9696,
      f1: 0.9555,
      auc: 0.9993,
      type: "classical",
      color: "#636e72",
      trainTime: 12.3,
    },
    "SVM": {
      accuracy: 0.9898,
      sensitivity: 0.9852,
      specificity: 0.9987,
      precision: 0.9907,
      f1: 0.9876,
      auc: 0.9998,
      type: "classical",
      color: "#b2bec3",
      trainTime: 28.7,
    },
    "XGBoost": {
      accuracy: 0.9848,
      sensitivity: 0.9778,
      specificity: 0.9981,
      precision: 0.9833,
      f1: 0.9802,
      auc: 0.9990,
      type: "classical",
      color: "#3b82f6",
      trainTime: 19.4,
    },
    "ResNet50": {
      accuracy: 0.9921,
      sensitivity: 0.9889,
      specificity: 0.9990,
      precision: 0.9923,
      f1: 0.9903,
      auc: 0.9999,
      type: "deep",
      color: "#6366f1",
      trainTime: 248.0,
    },
    "EfficientNet-B0": {
      accuracy: 0.9934,
      sensitivity: 0.9907,
      specificity: 0.9993,
      precision: 0.9937,
      f1: 0.9920,
      auc: 0.9999,
      type: "deep",
      color: "#4f46e5",
      trainTime: 193.5,
    },
    "Hybrid Ensemble": {
      accuracy: 0.9951,
      sensitivity: 0.9928,
      specificity: 0.9995,
      precision: 0.9953,
      f1: 0.9939,
      auc: 1.0000,
      type: "deep",
      color: "#2563eb",
      trainTime: 441.5,
    },
    "QuantumNow Optimized": {
      accuracy: 0.9963,
      sensitivity: 0.9944,
      specificity: 0.9997,
      precision: 0.9965,
      f1: 0.9953,
      auc: 1.0000,
      type: "quantum",
      color: "#1d4ed8",
      trainTime: 38.2,
    },
  },

  // ── Quantum Optimizer Convergence ──────────────────────────────────────
  optimizerConvergence: {
    evaluations: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    gridSearch: [
      0.5821, 0.6134, 0.6701, 0.7023, 0.7512,
      0.7921, 0.8102, 0.8231, 0.8341, 0.8411,
      0.8523, 0.8601, 0.8671, 0.8712, 0.8734
    ],
    randomSearch: [
      0.6234, 0.6891, 0.7445, 0.8012, 0.8234,
      0.8412, 0.8534, 0.8634, 0.8702, 0.8765,
      0.8798, 0.8821, 0.8845, 0.8857, 0.8863
    ],
    quantumNow: [
      0.7823, 0.8512, 0.8891, 0.9102, 0.9287,
      0.9401, 0.9487, 0.9543, 0.9578, 0.9601,
      0.9617, 0.9628, 0.9634, 0.9638, 0.9641
    ],
    finalFitness: {
      gridSearch: 0.8734,
      randomSearch: 0.8863,
      quantumNow: 0.9641,
    },
    executionTime: {
      gridSearch: 14.2,
      randomSearch: 12.8,
      quantumNow: 9.3,
    }
  },

  // ── Quantum Feature Selection ───────────────────────────────────────────
  featureSelection: {
    totalFeatures: 200,
    selectedFeatures: 87,
    generationHistory: [
      { gen: 1, fitness: 0.7234, features: 134 },
      { gen: 2, fitness: 0.8012, features: 112 },
      { gen: 3, fitness: 0.8645, features: 96  },
      { gen: 4, fitness: 0.9102, features: 91  },
      { gen: 5, fitness: 0.9287, features: 87  },
    ],
    validationAcc: 0.9287,
    validationF1: 0.9241,
  },

  // ── Preprocessing Pipeline Steps ────────────────────────────────────────
  preprocessingSteps: [
    {
      id: "read",
      name: "Image Read",
      icon: "01",
      description: "Load medical scan via SimpleITK or OpenCV. Handles DICOM, JPEG, PNG formats. 3D volumes sliced at midpoint.",
      tech: "SimpleITK / OpenCV",
      color: "#2563eb",
    },
    {
      id: "denoise",
      name: "Denoising",
      icon: "02",
      description: "Fast Non-Local Means Denoising (h=3) to eliminate scanner artifacts and reduce noise while preserving tissue edges.",
      tech: "cv2.fastNlMeansDenoising",
      color: "#4f46e5",
    },
    {
      id: "clahe",
      name: "CLAHE Enhancement",
      icon: "03",
      description: "Contrast Limited Adaptive Histogram Equalization (clip=2.0, grid=8×8) applied to LAB L-channel to reveal subtle tissue details.",
      tech: "cv2.createCLAHE",
      color: "#3b82f6",
    },
    {
      id: "contrast",
      name: "Contrast Adjust",
      icon: "04",
      description: "Linear contrast scaling (α=1.1, β=5) to enhance visual differentiation between healthy and abnormal tissue regions.",
      tech: "cv2.convertScaleAbs",
      color: "#f59e0b",
    },
    {
      id: "resize",
      name: "Resize 224×224",
      icon: "05",
      description: "Bilinear interpolation resize to 224×224 pixels, matching ResNet50 and EfficientNet-B0 input requirements.",
      tech: "cv2.INTER_LINEAR",
      color: "#10b981",
    },
    {
      id: "normalize",
      name: "Normalize",
      icon: "06",
      description: "Min-Max normalization to float32 [0, 1] range, then ImageNet mean/std standardization for transfer learning alignment.",
      tech: "numpy float32",
      color: "#059669",
    },
  ],

  // ── Augmentation Techniques ─────────────────────────────────────────────
  augmentations: [
    { name: "Random Rotation", detail: "±10°", icon: "ROT" },
    { name: "Horizontal Flip", detail: "p=0.5", icon: "HFL" },
    { name: "Vertical Flip", detail: "p=0.5", icon: "VFL" },
    { name: "Brightness Jitter", detail: "[0.9–1.1]", icon: "BRT" },
    { name: "Random Crop", detail: "scale [0.9–1.0]", icon: "CRP" },
  ],

};
